version: '2'

services:
      web:
        build:
          dockerfile: $PWD/../mlflow/Dockerfile
          context: $PWD/../mlflow
          
      mc:
        volumes:
            - $PWD/../mlflow/wait-for-it.sh:/tmp/wait-for-it.sh
